SELECT IF(TRUE,'1','0') FROM DUAL;
SELECT IF(FALSE,'1','0') FROM DUAL;
SELECT IFNULL(NULL,'1')FROM DUAL;
SELECT IFNULL('tom','1') FROM DUAL;

SELECT CASE 
	WHEN TRUE THEN 'tom'
	WHEN TRUE THEN 'jack'
	ELSE 'sali' END;
SELECT CASE 
	WHEN FALSE THEN 'tom'
	WHEN TRUE THEN 'jack'
	ELSE 'sali' END;
SELECT CASE 
	WHEN FALSE THEN 'tom'
	WHEN FALSE THEN 'jack'
	ELSE 'sali' END;
SELECT IF(comm IS NULL , 0.0,comm)
	FROM emp;
SELECT IFNULL(comm,0.0)
	FROM emp;
	
SELECT ename,(SELECT CASE
	WHEN job='CLEARK' THEN '职员'
	WHEN job='MANAGER' THEN '经理'
	WHEN job='SALESMAN' THEN '销售'
	ELSE job END) AS 'job'
	FROM emp;