CREATE TABLE t12(
	birthday DATE,
	job_day DATETIME,
	now_time TIMESTAMP
		NOT NULL DEFAULT CURRENT_TIMESTAMP 
		ON UPDATE CURRENT_TIMESTAMP
);

SELECT * FROM t12;
INSERT INTO t12(birthday,job_day)
		VALUES('2002-9-8','2002-9-8 12:23:33');
		
SELECT * FROM t12 (now_time);