SELECT CURRENT_DATE() FROM DUAL;
SELECT CURRENT_TIME() FROM DUAL;
SELECT CURRENT_TIMESTAMP() FROM DUAL;

CREATE TABLE mes(
	id INT,
	content VARCHAR(20),
	set_time DATETIME
);
SELECT * FROM mes;
INSERT INTO mes
	VALUES(1,'北极笑死',CURRENT_TIMESTAMP());
SELECT NOW() FROM DUAL;
SELECT id,content,DATE(set_time) FROM mes;
SELECT *
	FROM mes
	WHERE set_time>=DATE_SUB(NOW(),INTERVAL 10 MINUTE);
SELECT DATEDIFF('2021-12-30','2022-02-06') FROM DUAL;
SELECT DATEDIFF(NOW(),'2002-9-8') FROM DUAL;
SELECT DATEDIFF(DATE_ADD('2002-9-8',INTERVAL 80 YEAR),NOW()) FROM DUAL;
SELECT TIMEDIFF('10:10:10','12:15:45') FROM DUAL ;
SELECT YEAR(NOW()) FROM DUAL;
SELECT MONTH(NOW()) FROM DUAL;
SELECT DAY(NOW()) FROM DUAL;
SELECT MONTH(NOW()) FROM DUAL;
SELECT UNIX_TIMESTAMP() FROM DUAL;
SELECT FROM_UNIXTIME(1662902768,'%Y-%m-%d') FROM DUAL;

CREATE TABLE users(
	id INT, 
	‘name‘ VARCHAR(32) NOT NULL DEFAULT '',
	pwd CHAR(32) NOT NULL DEFAULT '');
SELECT USER() FROM DUAL;
SELECT DATABASE() FROM DUAL;
SELECT MD5('hwb0908hwb') FROM DUAL;
SELECT LENGTH(MD5('hwb0908hwb')) FROM DUAL;
SELECT PASSWORD('hwb0908hwb') FROM DUAL;
INSERT INTO users
	VALUES (111,'dd',MD5('hwb0908hwb'));
SELECT *FROM users;
SELECT * FROM users
	WHERE ‘name‘ = 'dd' AND pwd = MD5('hwb0908hwb'); 
SELECT * FROM mysql.user;
